/**: 
  ros__parameters:
    
    ###########################################
    # General node parameters 
    ###########################################
    DIM: 2               # Dimension of the space
    MANAGER_TIMER: 0.8   # Time at which the manager updates (seconds)
    AGENT_TIMER: 0.1     # frequency of the MPC (seconds)
    SPEED: 0.4           # Nominal speed of the agents
    BOX_WEIGHT: 10       # Weight of the boxes in the cost function
    COMM_DISTANCE: 2.    # Communication distance between agents
    HOOVERING_HEIGHT: 1. # Alitude at which the drones move nominally

    ###########################################################################################################
    # Specific of each agent. The agent number corresponds to the crazyflie number (check the tag on the drone).
    # N.B. Make sure that a drone with such number exists in the real fleet or in the simulation.
    ###########################################################################################################

    agent_1:
      pos:  [ -1.08,   -0.99,  0.3 ]
      radio: 0
      channel: 40

    agent_4:
      pos:  [ -1.1,  0.68,  0.3 ]
      radio: 0
      channel: 40

    agent_5:
      pos:  [ -0.52,  -0.18,  0.3 ]
      radio: 0
      channel: 40

    # agent_10:
    #   pos:  [ 0.6,  -1.4,  0.3 ]
    #   radio: 1
    #   channel: 80

    # agent_11:
    #   pos:  [ 0.6,  -0.20,  0.3 ]
    #   radio: 1
    #   channel: 80

    # agent_12:
    #   pos:  [ 0.6,  0.80,  0.3 ]
    #   radio: 1
    #   channel: 80

    

    ###########################################################################################################
    # Tasks specifications
    ###########################################################################################################

    # Tasks grouping by period
    PERIODS:
      period_0: [20.0, 25.0]
      period_1: [50.0, 65.0]
      period_2: [85.0, 90.0]

    TASKS:
      # PERIOD 0 — LETTER K
      # =======================
      # Origin (0,0) is the center of the K.
      task_1: 
        period_num: 0             # period at which the task is accomplished 
        edges: [1, 1]             # edge that defines the relative position (nb: make sure that an agent with the given number exists)
        rel_position: [0., 0.0]   # relative position with respect to the edge defined by the two agents
        size: 0.2                 # size of the task (radius of the area to be covered)
        type: "always"
      task_2: # Vertical Bottom
        period_num: 0
        edges: [1, 4]
        rel_position: [0., -.9]
        size: 0.2
        type: "always"
      task_3: # Midpoint/Joint
        period_num: 0
        edges: [1, 5]
        rel_position: [0., .9]
        size: 0.2
        type: "always"
      task_4: # Midpoint/Joint
        period_num: 0
        edges: [5, 12]
        rel_position: [-0.4, 0.]
        size: 0.2
        type: "always"
      task_5: # Midpoint/Joint
        period_num: 0
        edges: [1, 10]
        rel_position: [-0.5, .0]
        size: 0.2
        type: "always"
      task_6: # Midpoint/Joint
        period_num: 0
        edges: [10, 11]
        rel_position: [-0.4, 0.]
        size: 0.2
        type: "always"

 




     