import os

from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from ament_index_python.packages import get_package_share_directory

def generate_launch_description():
    # Replace this path with your actual package path if needed


    crazylie_setpoint_dir = get_package_share_directory('crazyflie_ros2_setpoint_follower')
    crazyswarm_pkg_path = get_package_share_directory('crazyflie')

    crazyflie_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(crazyswarm_pkg_path, "launch", "launch.py")
        ),
        launch_arguments={
            "crazyflies_yaml_file": os.path.join(
                crazylie_setpoint_dir,
                "config/hardware/crazyflie_autogenerated.yaml"
            ),
            "motion_capture_yaml_file": os.path.join(
                crazylie_setpoint_dir,
                "config/hardware/motion_capture.yaml"
            ),
            "teleop_yaml_file": os.path.join(
                crazylie_setpoint_dir,
                "config/hardware/teleop.yaml"
            ),
            "server_yaml_file": os.path.join(
                crazylie_setpoint_dir,
                "config/hardware/server.yaml"
            ),

            "teleop":"false",
            "gui": "false",
            "backend": "cpp",
        }.items()
    )

    return LaunchDescription([crazyflie_launch])