/**: 
  ros__parameters:
    robot_prefix: '/crazyflie'
    use_sim_time: true

    SYSTEM: 0 #0: SIM or 1: REAL
    DIM: 2
    NUM_AGENTS: 10

    MAIN_TIMER: 0.1
    SETPOINT_TIMER: 0.1
    AGENT_TIMER: 0.05
    SPEED: 0.4
    BOX_WEIGHT: 10
    COMM_DISTANCE: 3.

    SIDE_LENGTH: 10.0
    ARENA_SIZE: 100.0
    MAX_INPUT: 10.0
    HOOVERING_HEIGHT: 1.

    POSITIONS:
      POS_1:  [ 2.0,   0.5,  0.0 ]
      POS_2:  [ 2.0,  -0.5,  0.0 ]
      POS_3:  [ 0.33,  2.0,  0.0 ]
      POS_4:  [ 0.33,  0.0,  0.0 ]
      POS_5:  [ 0.33, -2.0,  0.0 ]
      POS_6:  [ -0.33,  2.0,  0.0 ]
      POS_7:  [ -0.33,  0.0,  0.0 ]
      POS_8:  [ -0.33, -2.0,  0.0 ]
      POS_9:  [ -2.0,   0.5,  0.0 ]
      POS_10: [ -2.0,  -0.5,  0.0 ]

    PERIODS:
      period_0: [20.0, 35.0] # Letter A
      period_1: [45.0, 60.0] # Letter B
      period_2: [70.0, 85.0] # Letter C

    TASKS:
      # PERIOD 0 — LETTER A
      # =======================
      task_1: # Left leg bottom to peak
        period_num: 0
        edges: [1, 2]
        rel_position: [-1.5, -2.0] 
        size: 0.2
      task_2: # Peak
        period_num: 0
        edges: [2, 3]
        rel_position: [0.0, 2.0]
        size: 0.2
      task_3: # Right leg peak to bottom
        period_num: 0
        edges: [3, 4]
        rel_position: [1.5, -2.0]
        size: 0.2
      task_4: # Horizontal bar
        period_num: 0
        edges: [5, 6]
        rel_position: [0.0, 0.0] # Centered bar
        size: 0.2

      # PERIOD 1 — LETTER B
      # =======================
      task_5: # Vertical Spine (Top Half)
        period_num: 1
        edges: [1, 2]
        rel_position: [-1.5, 0.0] 
        size: 0.2
      task_6: # Vertical Spine (Bottom Half)
        period_num: 1
        edges: [2, 3]
        rel_position: [-1.5, 0.0] 
        size: 0.2
      task_7: # Top Curve Peak
        period_num: 1
        edges: [1, 4]
        rel_position: [-0.75, -1.5]
        size: 0.2
      task_8: # Middle Joint (Connecting Top Loop)
        period_num: 1
        edges: [2, 4]
        rel_position: [0.75, -1.5]
        size: 0.2
      task_9: # Middle Joint (Connecting Bottom Loop)
        period_num: 1
        edges: [2, 5]
        rel_position: [-0.75, -1.5]
        size: 0.2
      task_10: # Bottom Curve Peak
        period_num: 1
        edges: [3, 5]
        rel_position: [0.75, -1.5]
        size: 0.2

      # PERIOD 2 — LETTER C
      # =======================
      task_11: # Top Right Tip
        period_num: 2
        edges: [1, 2]
        rel_position: [1.5, 1.5] 
        size: 0.2
      task_12: # Top Left Curve
        period_num: 2
        edges: [2, 3]
        rel_position: [-1.5, 1.5]
        size: 0.2
      task_13: # Bottom Left Curve
        period_num: 2
        edges: [3, 4]
        rel_position: [-1.5, -1.5]
        size: 0.2
      task_14: # Bottom Right Tip
        period_num: 2
        edges: [4, 5]
        rel_position: [1.5, -1.5]
        size: 0.2