/**: 
  ros__parameters:
    SYSTEM: 1 #0: SIM or 1: REAL
    DIM: 2
    NUM_AGENTS: 4
    MAIN_TIMER: 0.1
    SETPOINT_TIMER: 0.1
    AGENT_TIMER: 0.02
    SPEED: 0.3
    COMM_DISTANCE: 1.1

    SIDE_LENGTH: 10.
    ARENA_SIZE: 100.
    MAX_INPUT: 10.