/**: 
  ros__parameters:
    robot_prefix: '/crazyflie'
    use_sim_time: true

    SYSTEM: 1 #0: SIM or 1: REAL
    DIM: 2
    NUM_AGENTS: 2

    MANAGER_TIMER: 0.8
    AGENT_TIMER: 0.05
    SPEED: 0.4
    BOX_WEIGHT: 10
    COMM_DISTANCE: 5.

    SIDE_LENGTH: 10.0
    ARENA_SIZE: 100.0
    MAX_INPUT: 10.0
    HOOVERING_HEIGHT: 1.

    PERIODS:
      period_0: [20.0, 35.0] # Letter A

    TASKS:
      # PERIOD 0 — LETTER A
      # =======================
      task_1: # Left leg bottom to peak
        period_num: 0
        edges: [1, 2]
        rel_position: [-2., 0.] 
        size: 0.2